version: '3'
services:
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront

  todofront:
    image: todofront
    depends_on:
      - todoback
    ports:
      - "3000:3000"

  todoback:
    image: todoback
    depends_on:
      - todofront
    ports:
      - "3001:3001"
